

(use-modules (ice-9 format)) ;; format common lisp 
(use-modules (ice-9 pretty-print)) ;; pretty-print
(define pp pretty-print)
;;(use-modules (rnrs)) ;; assert 
(use-modules (srfi srfi-1)) ;; first second third ...
(use-modules (srfi srfi-2)) ;; first second third ...

(use-modules (rnrs)) ;; assert



;; regular expression
(use-modules (ice-9 regex)) 

;; pattern matcher ?
(use-modules (ice-9 match))

;; --------------------- macros --------------------------
(define-macro (dolist varls . body)
  (let* ((fn (gensym "fn"))
	 (xs (gensym "xs"))
	 (var (car varls))
	 (ls  (car (cdr varls))))
    `(letrec ((,fn (lambda (,xs)
		     (cond
		      ((null? ,xs) #f)
		      (#t (let ((,var (car ,xs)))
			    ,@body
			    (,fn (cdr ,xs))))))))
       (,fn ,ls))))

;; --------------------- while ----------------------------

(defmacro while (condition . body)
  (let ((lup (gensym "loop")))
    `(letrec ((,lup (lambda ()
		      (when ,condition
			,@body
			(,lup)))))
       (,lup))))

;; (let ((i 0))
;;   (while (< i 10)
;;     (format #t " i = ~a ~%" i )
;;     (set!  i (+ i 1))))

;; --------------------- macros --------------------------

(define *debug* #f)

(define input #f)

(define (get-input filename)
  (let ((port (open-input-file filename)))
    (set! input (read port))
    (close-input-port port)))

;; for example
;;(define input #f)

(get-input "input")
;;(get-input "input2")

(define (pair-repeat s)
  (or
(string-match "aa.*aa" s) 
(string-match "ab.*ab" s) 
(string-match "ac.*ac" s) 
(string-match "ad.*ad" s) 
(string-match "ae.*ae" s) 
(string-match "af.*af" s) 
(string-match "ag.*ag" s) 
(string-match "ah.*ah" s) 
(string-match "ai.*ai" s) 
(string-match "aj.*aj" s) 
(string-match "ak.*ak" s) 
(string-match "al.*al" s) 
(string-match "am.*am" s) 
(string-match "an.*an" s) 
(string-match "ao.*ao" s) 
(string-match "ap.*ap" s) 
(string-match "aq.*aq" s) 
(string-match "ar.*ar" s) 
(string-match "as.*as" s) 
(string-match "at.*at" s) 
(string-match "au.*au" s) 
(string-match "av.*av" s) 
(string-match "aw.*aw" s) 
(string-match "ax.*ax" s) 
(string-match "ay.*ay" s) 
(string-match "az.*az" s) 
(string-match "ba.*ba" s) 
(string-match "bb.*bb" s) 
(string-match "bc.*bc" s) 
(string-match "bd.*bd" s) 
(string-match "be.*be" s) 
(string-match "bf.*bf" s) 
(string-match "bg.*bg" s) 
(string-match "bh.*bh" s) 
(string-match "bi.*bi" s) 
(string-match "bj.*bj" s) 
(string-match "bk.*bk" s) 
(string-match "bl.*bl" s) 
(string-match "bm.*bm" s) 
(string-match "bn.*bn" s) 
(string-match "bo.*bo" s) 
(string-match "bp.*bp" s) 
(string-match "bq.*bq" s) 
(string-match "br.*br" s) 
(string-match "bs.*bs" s) 
(string-match "bt.*bt" s) 
(string-match "bu.*bu" s) 
(string-match "bv.*bv" s) 
(string-match "bw.*bw" s) 
(string-match "bx.*bx" s) 
(string-match "by.*by" s) 
(string-match "bz.*bz" s) 
(string-match "ca.*ca" s) 
(string-match "cb.*cb" s) 
(string-match "cc.*cc" s) 
(string-match "cd.*cd" s) 
(string-match "ce.*ce" s) 
(string-match "cf.*cf" s) 
(string-match "cg.*cg" s) 
(string-match "ch.*ch" s) 
(string-match "ci.*ci" s) 
(string-match "cj.*cj" s) 
(string-match "ck.*ck" s) 
(string-match "cl.*cl" s) 
(string-match "cm.*cm" s) 
(string-match "cn.*cn" s) 
(string-match "co.*co" s) 
(string-match "cp.*cp" s) 
(string-match "cq.*cq" s) 
(string-match "cr.*cr" s) 
(string-match "cs.*cs" s) 
(string-match "ct.*ct" s) 
(string-match "cu.*cu" s) 
(string-match "cv.*cv" s) 
(string-match "cw.*cw" s) 
(string-match "cx.*cx" s) 
(string-match "cy.*cy" s) 
(string-match "cz.*cz" s) 
(string-match "da.*da" s) 
(string-match "db.*db" s) 
(string-match "dc.*dc" s) 
(string-match "dd.*dd" s) 
(string-match "de.*de" s) 
(string-match "df.*df" s) 
(string-match "dg.*dg" s) 
(string-match "dh.*dh" s) 
(string-match "di.*di" s) 
(string-match "dj.*dj" s) 
(string-match "dk.*dk" s) 
(string-match "dl.*dl" s) 
(string-match "dm.*dm" s) 
(string-match "dn.*dn" s) 
(string-match "do.*do" s) 
(string-match "dp.*dp" s) 
(string-match "dq.*dq" s) 
(string-match "dr.*dr" s) 
(string-match "ds.*ds" s) 
(string-match "dt.*dt" s) 
(string-match "du.*du" s) 
(string-match "dv.*dv" s) 
(string-match "dw.*dw" s) 
(string-match "dx.*dx" s) 
(string-match "dy.*dy" s) 
(string-match "dz.*dz" s) 
(string-match "ea.*ea" s) 
(string-match "eb.*eb" s) 
(string-match "ec.*ec" s) 
(string-match "ed.*ed" s) 
(string-match "ee.*ee" s) 
(string-match "ef.*ef" s) 
(string-match "eg.*eg" s) 
(string-match "eh.*eh" s) 
(string-match "ei.*ei" s) 
(string-match "ej.*ej" s) 
(string-match "ek.*ek" s) 
(string-match "el.*el" s) 
(string-match "em.*em" s) 
(string-match "en.*en" s) 
(string-match "eo.*eo" s) 
(string-match "ep.*ep" s) 
(string-match "eq.*eq" s) 
(string-match "er.*er" s) 
(string-match "es.*es" s) 
(string-match "et.*et" s) 
(string-match "eu.*eu" s) 
(string-match "ev.*ev" s) 
(string-match "ew.*ew" s) 
(string-match "ex.*ex" s) 
(string-match "ey.*ey" s) 
(string-match "ez.*ez" s) 
(string-match "fa.*fa" s) 
(string-match "fb.*fb" s) 
(string-match "fc.*fc" s) 
(string-match "fd.*fd" s) 
(string-match "fe.*fe" s) 
(string-match "ff.*ff" s) 
(string-match "fg.*fg" s) 
(string-match "fh.*fh" s) 
(string-match "fi.*fi" s) 
(string-match "fj.*fj" s) 
(string-match "fk.*fk" s) 
(string-match "fl.*fl" s) 
(string-match "fm.*fm" s) 
(string-match "fn.*fn" s) 
(string-match "fo.*fo" s) 
(string-match "fp.*fp" s) 
(string-match "fq.*fq" s) 
(string-match "fr.*fr" s) 
(string-match "fs.*fs" s) 
(string-match "ft.*ft" s) 
(string-match "fu.*fu" s) 
(string-match "fv.*fv" s) 
(string-match "fw.*fw" s) 
(string-match "fx.*fx" s) 
(string-match "fy.*fy" s) 
(string-match "fz.*fz" s) 
(string-match "ga.*ga" s) 
(string-match "gb.*gb" s) 
(string-match "gc.*gc" s) 
(string-match "gd.*gd" s) 
(string-match "ge.*ge" s) 
(string-match "gf.*gf" s) 
(string-match "gg.*gg" s) 
(string-match "gh.*gh" s) 
(string-match "gi.*gi" s) 
(string-match "gj.*gj" s) 
(string-match "gk.*gk" s) 
(string-match "gl.*gl" s) 
(string-match "gm.*gm" s) 
(string-match "gn.*gn" s) 
(string-match "go.*go" s) 
(string-match "gp.*gp" s) 
(string-match "gq.*gq" s) 
(string-match "gr.*gr" s) 
(string-match "gs.*gs" s) 
(string-match "gt.*gt" s) 
(string-match "gu.*gu" s) 
(string-match "gv.*gv" s) 
(string-match "gw.*gw" s) 
(string-match "gx.*gx" s) 
(string-match "gy.*gy" s) 
(string-match "gz.*gz" s) 
(string-match "ha.*ha" s) 
(string-match "hb.*hb" s) 
(string-match "hc.*hc" s) 
(string-match "hd.*hd" s) 
(string-match "he.*he" s) 
(string-match "hf.*hf" s) 
(string-match "hg.*hg" s) 
(string-match "hh.*hh" s) 
(string-match "hi.*hi" s) 
(string-match "hj.*hj" s) 
(string-match "hk.*hk" s) 
(string-match "hl.*hl" s) 
(string-match "hm.*hm" s) 
(string-match "hn.*hn" s) 
(string-match "ho.*ho" s) 
(string-match "hp.*hp" s) 
(string-match "hq.*hq" s) 
(string-match "hr.*hr" s) 
(string-match "hs.*hs" s) 
(string-match "ht.*ht" s) 
(string-match "hu.*hu" s) 
(string-match "hv.*hv" s) 
(string-match "hw.*hw" s) 
(string-match "hx.*hx" s) 
(string-match "hy.*hy" s) 
(string-match "hz.*hz" s) 
(string-match "ia.*ia" s) 
(string-match "ib.*ib" s) 
(string-match "ic.*ic" s) 
(string-match "id.*id" s) 
(string-match "ie.*ie" s) 
(string-match "if.*if" s) 
(string-match "ig.*ig" s) 
(string-match "ih.*ih" s) 
(string-match "ii.*ii" s) 
(string-match "ij.*ij" s) 
(string-match "ik.*ik" s) 
(string-match "il.*il" s) 
(string-match "im.*im" s) 
(string-match "in.*in" s) 
(string-match "io.*io" s) 
(string-match "ip.*ip" s) 
(string-match "iq.*iq" s) 
(string-match "ir.*ir" s) 
(string-match "is.*is" s) 
(string-match "it.*it" s) 
(string-match "iu.*iu" s) 
(string-match "iv.*iv" s) 
(string-match "iw.*iw" s) 
(string-match "ix.*ix" s) 
(string-match "iy.*iy" s) 
(string-match "iz.*iz" s) 
(string-match "ja.*ja" s) 
(string-match "jb.*jb" s) 
(string-match "jc.*jc" s) 
(string-match "jd.*jd" s) 
(string-match "je.*je" s) 
(string-match "jf.*jf" s) 
(string-match "jg.*jg" s) 
(string-match "jh.*jh" s) 
(string-match "ji.*ji" s) 
(string-match "jj.*jj" s) 
(string-match "jk.*jk" s) 
(string-match "jl.*jl" s) 
(string-match "jm.*jm" s) 
(string-match "jn.*jn" s) 
(string-match "jo.*jo" s) 
(string-match "jp.*jp" s) 
(string-match "jq.*jq" s) 
(string-match "jr.*jr" s) 
(string-match "js.*js" s) 
(string-match "jt.*jt" s) 
(string-match "ju.*ju" s) 
(string-match "jv.*jv" s) 
(string-match "jw.*jw" s) 
(string-match "jx.*jx" s) 
(string-match "jy.*jy" s) 
(string-match "jz.*jz" s) 
(string-match "ka.*ka" s) 
(string-match "kb.*kb" s) 
(string-match "kc.*kc" s) 
(string-match "kd.*kd" s) 
(string-match "ke.*ke" s) 
(string-match "kf.*kf" s) 
(string-match "kg.*kg" s) 
(string-match "kh.*kh" s) 
(string-match "ki.*ki" s) 
(string-match "kj.*kj" s) 
(string-match "kk.*kk" s) 
(string-match "kl.*kl" s) 
(string-match "km.*km" s) 
(string-match "kn.*kn" s) 
(string-match "ko.*ko" s) 
(string-match "kp.*kp" s) 
(string-match "kq.*kq" s) 
(string-match "kr.*kr" s) 
(string-match "ks.*ks" s) 
(string-match "kt.*kt" s) 
(string-match "ku.*ku" s) 
(string-match "kv.*kv" s) 
(string-match "kw.*kw" s) 
(string-match "kx.*kx" s) 
(string-match "ky.*ky" s) 
(string-match "kz.*kz" s) 
(string-match "la.*la" s) 
(string-match "lb.*lb" s) 
(string-match "lc.*lc" s) 
(string-match "ld.*ld" s) 
(string-match "le.*le" s) 
(string-match "lf.*lf" s) 
(string-match "lg.*lg" s) 
(string-match "lh.*lh" s) 
(string-match "li.*li" s) 
(string-match "lj.*lj" s) 
(string-match "lk.*lk" s) 
(string-match "ll.*ll" s) 
(string-match "lm.*lm" s) 
(string-match "ln.*ln" s) 
(string-match "lo.*lo" s) 
(string-match "lp.*lp" s) 
(string-match "lq.*lq" s) 
(string-match "lr.*lr" s) 
(string-match "ls.*ls" s) 
(string-match "lt.*lt" s) 
(string-match "lu.*lu" s) 
(string-match "lv.*lv" s) 
(string-match "lw.*lw" s) 
(string-match "lx.*lx" s) 
(string-match "ly.*ly" s) 
(string-match "lz.*lz" s) 
(string-match "ma.*ma" s) 
(string-match "mb.*mb" s) 
(string-match "mc.*mc" s) 
(string-match "md.*md" s) 
(string-match "me.*me" s) 
(string-match "mf.*mf" s) 
(string-match "mg.*mg" s) 
(string-match "mh.*mh" s) 
(string-match "mi.*mi" s) 
(string-match "mj.*mj" s) 
(string-match "mk.*mk" s) 
(string-match "ml.*ml" s) 
(string-match "mm.*mm" s) 
(string-match "mn.*mn" s) 
(string-match "mo.*mo" s) 
(string-match "mp.*mp" s) 
(string-match "mq.*mq" s) 
(string-match "mr.*mr" s) 
(string-match "ms.*ms" s) 
(string-match "mt.*mt" s) 
(string-match "mu.*mu" s) 
(string-match "mv.*mv" s) 
(string-match "mw.*mw" s) 
(string-match "mx.*mx" s) 
(string-match "my.*my" s) 
(string-match "mz.*mz" s) 
(string-match "na.*na" s) 
(string-match "nb.*nb" s) 
(string-match "nc.*nc" s) 
(string-match "nd.*nd" s) 
(string-match "ne.*ne" s) 
(string-match "nf.*nf" s) 
(string-match "ng.*ng" s) 
(string-match "nh.*nh" s) 
(string-match "ni.*ni" s) 
(string-match "nj.*nj" s) 
(string-match "nk.*nk" s) 
(string-match "nl.*nl" s) 
(string-match "nm.*nm" s) 
(string-match "nn.*nn" s) 
(string-match "no.*no" s) 
(string-match "np.*np" s) 
(string-match "nq.*nq" s) 
(string-match "nr.*nr" s) 
(string-match "ns.*ns" s) 
(string-match "nt.*nt" s) 
(string-match "nu.*nu" s) 
(string-match "nv.*nv" s) 
(string-match "nw.*nw" s) 
(string-match "nx.*nx" s) 
(string-match "ny.*ny" s) 
(string-match "nz.*nz" s) 
(string-match "oa.*oa" s) 
(string-match "ob.*ob" s) 
(string-match "oc.*oc" s) 
(string-match "od.*od" s) 
(string-match "oe.*oe" s) 
(string-match "of.*of" s) 
(string-match "og.*og" s) 
(string-match "oh.*oh" s) 
(string-match "oi.*oi" s) 
(string-match "oj.*oj" s) 
(string-match "ok.*ok" s) 
(string-match "ol.*ol" s) 
(string-match "om.*om" s) 
(string-match "on.*on" s) 
(string-match "oo.*oo" s) 
(string-match "op.*op" s) 
(string-match "oq.*oq" s) 
(string-match "or.*or" s) 
(string-match "os.*os" s) 
(string-match "ot.*ot" s) 
(string-match "ou.*ou" s) 
(string-match "ov.*ov" s) 
(string-match "ow.*ow" s) 
(string-match "ox.*ox" s) 
(string-match "oy.*oy" s) 
(string-match "oz.*oz" s) 
(string-match "pa.*pa" s) 
(string-match "pb.*pb" s) 
(string-match "pc.*pc" s) 
(string-match "pd.*pd" s) 
(string-match "pe.*pe" s) 
(string-match "pf.*pf" s) 
(string-match "pg.*pg" s) 
(string-match "ph.*ph" s) 
(string-match "pi.*pi" s) 
(string-match "pj.*pj" s) 
(string-match "pk.*pk" s) 
(string-match "pl.*pl" s) 
(string-match "pm.*pm" s) 
(string-match "pn.*pn" s) 
(string-match "po.*po" s) 
(string-match "pp.*pp" s) 
(string-match "pq.*pq" s) 
(string-match "pr.*pr" s) 
(string-match "ps.*ps" s) 
(string-match "pt.*pt" s) 
(string-match "pu.*pu" s) 
(string-match "pv.*pv" s) 
(string-match "pw.*pw" s) 
(string-match "px.*px" s) 
(string-match "py.*py" s) 
(string-match "pz.*pz" s) 
(string-match "qa.*qa" s) 
(string-match "qb.*qb" s) 
(string-match "qc.*qc" s) 
(string-match "qd.*qd" s) 
(string-match "qe.*qe" s) 
(string-match "qf.*qf" s) 
(string-match "qg.*qg" s) 
(string-match "qh.*qh" s) 
(string-match "qi.*qi" s) 
(string-match "qj.*qj" s) 
(string-match "qk.*qk" s) 
(string-match "ql.*ql" s) 
(string-match "qm.*qm" s) 
(string-match "qn.*qn" s) 
(string-match "qo.*qo" s) 
(string-match "qp.*qp" s) 
(string-match "qq.*qq" s) 
(string-match "qr.*qr" s) 
(string-match "qs.*qs" s) 
(string-match "qt.*qt" s) 
(string-match "qu.*qu" s) 
(string-match "qv.*qv" s) 
(string-match "qw.*qw" s) 
(string-match "qx.*qx" s) 
(string-match "qy.*qy" s) 
(string-match "qz.*qz" s) 
(string-match "ra.*ra" s) 
(string-match "rb.*rb" s) 
(string-match "rc.*rc" s) 
(string-match "rd.*rd" s) 
(string-match "re.*re" s) 
(string-match "rf.*rf" s) 
(string-match "rg.*rg" s) 
(string-match "rh.*rh" s) 
(string-match "ri.*ri" s) 
(string-match "rj.*rj" s) 
(string-match "rk.*rk" s) 
(string-match "rl.*rl" s) 
(string-match "rm.*rm" s) 
(string-match "rn.*rn" s) 
(string-match "ro.*ro" s) 
(string-match "rp.*rp" s) 
(string-match "rq.*rq" s) 
(string-match "rr.*rr" s) 
(string-match "rs.*rs" s) 
(string-match "rt.*rt" s) 
(string-match "ru.*ru" s) 
(string-match "rv.*rv" s) 
(string-match "rw.*rw" s) 
(string-match "rx.*rx" s) 
(string-match "ry.*ry" s) 
(string-match "rz.*rz" s) 
(string-match "sa.*sa" s) 
(string-match "sb.*sb" s) 
(string-match "sc.*sc" s) 
(string-match "sd.*sd" s) 
(string-match "se.*se" s) 
(string-match "sf.*sf" s) 
(string-match "sg.*sg" s) 
(string-match "sh.*sh" s) 
(string-match "si.*si" s) 
(string-match "sj.*sj" s) 
(string-match "sk.*sk" s) 
(string-match "sl.*sl" s) 
(string-match "sm.*sm" s) 
(string-match "sn.*sn" s) 
(string-match "so.*so" s) 
(string-match "sp.*sp" s) 
(string-match "sq.*sq" s) 
(string-match "sr.*sr" s) 
(string-match "ss.*ss" s) 
(string-match "st.*st" s) 
(string-match "su.*su" s) 
(string-match "sv.*sv" s) 
(string-match "sw.*sw" s) 
(string-match "sx.*sx" s) 
(string-match "sy.*sy" s) 
(string-match "sz.*sz" s) 
(string-match "ta.*ta" s) 
(string-match "tb.*tb" s) 
(string-match "tc.*tc" s) 
(string-match "td.*td" s) 
(string-match "te.*te" s) 
(string-match "tf.*tf" s) 
(string-match "tg.*tg" s) 
(string-match "th.*th" s) 
(string-match "ti.*ti" s) 
(string-match "tj.*tj" s) 
(string-match "tk.*tk" s) 
(string-match "tl.*tl" s) 
(string-match "tm.*tm" s) 
(string-match "tn.*tn" s) 
(string-match "to.*to" s) 
(string-match "tp.*tp" s) 
(string-match "tq.*tq" s) 
(string-match "tr.*tr" s) 
(string-match "ts.*ts" s) 
(string-match "tt.*tt" s) 
(string-match "tu.*tu" s) 
(string-match "tv.*tv" s) 
(string-match "tw.*tw" s) 
(string-match "tx.*tx" s) 
(string-match "ty.*ty" s) 
(string-match "tz.*tz" s) 
(string-match "ua.*ua" s) 
(string-match "ub.*ub" s) 
(string-match "uc.*uc" s) 
(string-match "ud.*ud" s) 
(string-match "ue.*ue" s) 
(string-match "uf.*uf" s) 
(string-match "ug.*ug" s) 
(string-match "uh.*uh" s) 
(string-match "ui.*ui" s) 
(string-match "uj.*uj" s) 
(string-match "uk.*uk" s) 
(string-match "ul.*ul" s) 
(string-match "um.*um" s) 
(string-match "un.*un" s) 
(string-match "uo.*uo" s) 
(string-match "up.*up" s) 
(string-match "uq.*uq" s) 
(string-match "ur.*ur" s) 
(string-match "us.*us" s) 
(string-match "ut.*ut" s) 
(string-match "uu.*uu" s) 
(string-match "uv.*uv" s) 
(string-match "uw.*uw" s) 
(string-match "ux.*ux" s) 
(string-match "uy.*uy" s) 
(string-match "uz.*uz" s) 
(string-match "va.*va" s) 
(string-match "vb.*vb" s) 
(string-match "vc.*vc" s) 
(string-match "vd.*vd" s) 
(string-match "ve.*ve" s) 
(string-match "vf.*vf" s) 
(string-match "vg.*vg" s) 
(string-match "vh.*vh" s) 
(string-match "vi.*vi" s) 
(string-match "vj.*vj" s) 
(string-match "vk.*vk" s) 
(string-match "vl.*vl" s) 
(string-match "vm.*vm" s) 
(string-match "vn.*vn" s) 
(string-match "vo.*vo" s) 
(string-match "vp.*vp" s) 
(string-match "vq.*vq" s) 
(string-match "vr.*vr" s) 
(string-match "vs.*vs" s) 
(string-match "vt.*vt" s) 
(string-match "vu.*vu" s) 
(string-match "vv.*vv" s) 
(string-match "vw.*vw" s) 
(string-match "vx.*vx" s) 
(string-match "vy.*vy" s) 
(string-match "vz.*vz" s) 
(string-match "wa.*wa" s) 
(string-match "wb.*wb" s) 
(string-match "wc.*wc" s) 
(string-match "wd.*wd" s) 
(string-match "we.*we" s) 
(string-match "wf.*wf" s) 
(string-match "wg.*wg" s) 
(string-match "wh.*wh" s) 
(string-match "wi.*wi" s) 
(string-match "wj.*wj" s) 
(string-match "wk.*wk" s) 
(string-match "wl.*wl" s) 
(string-match "wm.*wm" s) 
(string-match "wn.*wn" s) 
(string-match "wo.*wo" s) 
(string-match "wp.*wp" s) 
(string-match "wq.*wq" s) 
(string-match "wr.*wr" s) 
(string-match "ws.*ws" s) 
(string-match "wt.*wt" s) 
(string-match "wu.*wu" s) 
(string-match "wv.*wv" s) 
(string-match "ww.*ww" s) 
(string-match "wx.*wx" s) 
(string-match "wy.*wy" s) 
(string-match "wz.*wz" s) 
(string-match "xa.*xa" s) 
(string-match "xb.*xb" s) 
(string-match "xc.*xc" s) 
(string-match "xd.*xd" s) 
(string-match "xe.*xe" s) 
(string-match "xf.*xf" s) 
(string-match "xg.*xg" s) 
(string-match "xh.*xh" s) 
(string-match "xi.*xi" s) 
(string-match "xj.*xj" s) 
(string-match "xk.*xk" s) 
(string-match "xl.*xl" s) 
(string-match "xm.*xm" s) 
(string-match "xn.*xn" s) 
(string-match "xo.*xo" s) 
(string-match "xp.*xp" s) 
(string-match "xq.*xq" s) 
(string-match "xr.*xr" s) 
(string-match "xs.*xs" s) 
(string-match "xt.*xt" s) 
(string-match "xu.*xu" s) 
(string-match "xv.*xv" s) 
(string-match "xw.*xw" s) 
(string-match "xx.*xx" s) 
(string-match "xy.*xy" s) 
(string-match "xz.*xz" s) 
(string-match "ya.*ya" s) 
(string-match "yb.*yb" s) 
(string-match "yc.*yc" s) 
(string-match "yd.*yd" s) 
(string-match "ye.*ye" s) 
(string-match "yf.*yf" s) 
(string-match "yg.*yg" s) 
(string-match "yh.*yh" s) 
(string-match "yi.*yi" s) 
(string-match "yj.*yj" s) 
(string-match "yk.*yk" s) 
(string-match "yl.*yl" s) 
(string-match "ym.*ym" s) 
(string-match "yn.*yn" s) 
(string-match "yo.*yo" s) 
(string-match "yp.*yp" s) 
(string-match "yq.*yq" s) 
(string-match "yr.*yr" s) 
(string-match "ys.*ys" s) 
(string-match "yt.*yt" s) 
(string-match "yu.*yu" s) 
(string-match "yv.*yv" s) 
(string-match "yw.*yw" s) 
(string-match "yx.*yx" s) 
(string-match "yy.*yy" s) 
(string-match "yz.*yz" s) 
(string-match "za.*za" s) 
(string-match "zb.*zb" s) 
(string-match "zc.*zc" s) 
(string-match "zd.*zd" s) 
(string-match "ze.*ze" s) 
(string-match "zf.*zf" s) 
(string-match "zg.*zg" s) 
(string-match "zh.*zh" s) 
(string-match "zi.*zi" s) 
(string-match "zj.*zj" s) 
(string-match "zk.*zk" s) 
(string-match "zl.*zl" s) 
(string-match "zm.*zm" s) 
(string-match "zn.*zn" s) 
(string-match "zo.*zo" s) 
(string-match "zp.*zp" s) 
(string-match "zq.*zq" s) 
(string-match "zr.*zr" s) 
(string-match "zs.*zs" s) 
(string-match "zt.*zt" s) 
(string-match "zu.*zu" s) 
(string-match "zv.*zv" s) 
(string-match "zw.*zw" s) 
(string-match "zx.*zx" s) 
(string-match "zy.*zy" s) 
(string-match "zz.*zz" s)
   
))


(define (piggy-middle s)
  (or
   (string-match "aaa" s) 
(string-match "aba" s) 
(string-match "aca" s) 
(string-match "ada" s) 
(string-match "aea" s) 
(string-match "afa" s) 
(string-match "aga" s) 
(string-match "aha" s) 
(string-match "aia" s) 
(string-match "aja" s) 
(string-match "aka" s) 
(string-match "ala" s) 
(string-match "ama" s) 
(string-match "ana" s) 
(string-match "aoa" s) 
(string-match "apa" s) 
(string-match "aqa" s) 
(string-match "ara" s) 
(string-match "asa" s) 
(string-match "ata" s) 
(string-match "aua" s) 
(string-match "ava" s) 
(string-match "awa" s) 
(string-match "axa" s) 
(string-match "aya" s) 
(string-match "aza" s) 
(string-match "bab" s) 
(string-match "bbb" s) 
(string-match "bcb" s) 
(string-match "bdb" s) 
(string-match "beb" s) 
(string-match "bfb" s) 
(string-match "bgb" s) 
(string-match "bhb" s) 
(string-match "bib" s) 
(string-match "bjb" s) 
(string-match "bkb" s) 
(string-match "blb" s) 
(string-match "bmb" s) 
(string-match "bnb" s) 
(string-match "bob" s) 
(string-match "bpb" s) 
(string-match "bqb" s) 
(string-match "brb" s) 
(string-match "bsb" s) 
(string-match "btb" s) 
(string-match "bub" s) 
(string-match "bvb" s) 
(string-match "bwb" s) 
(string-match "bxb" s) 
(string-match "byb" s) 
(string-match "bzb" s) 
(string-match "cac" s) 
(string-match "cbc" s) 
(string-match "ccc" s) 
(string-match "cdc" s) 
(string-match "cec" s) 
(string-match "cfc" s) 
(string-match "cgc" s) 
(string-match "chc" s) 
(string-match "cic" s) 
(string-match "cjc" s) 
(string-match "ckc" s) 
(string-match "clc" s) 
(string-match "cmc" s) 
(string-match "cnc" s) 
(string-match "coc" s) 
(string-match "cpc" s) 
(string-match "cqc" s) 
(string-match "crc" s) 
(string-match "csc" s) 
(string-match "ctc" s) 
(string-match "cuc" s) 
(string-match "cvc" s) 
(string-match "cwc" s) 
(string-match "cxc" s) 
(string-match "cyc" s) 
(string-match "czc" s) 
(string-match "dad" s) 
(string-match "dbd" s) 
(string-match "dcd" s) 
(string-match "ddd" s) 
(string-match "ded" s) 
(string-match "dfd" s) 
(string-match "dgd" s) 
(string-match "dhd" s) 
(string-match "did" s) 
(string-match "djd" s) 
(string-match "dkd" s) 
(string-match "dld" s) 
(string-match "dmd" s) 
(string-match "dnd" s) 
(string-match "dod" s) 
(string-match "dpd" s) 
(string-match "dqd" s) 
(string-match "drd" s) 
(string-match "dsd" s) 
(string-match "dtd" s) 
(string-match "dud" s) 
(string-match "dvd" s) 
(string-match "dwd" s) 
(string-match "dxd" s) 
(string-match "dyd" s) 
(string-match "dzd" s) 
(string-match "eae" s) 
(string-match "ebe" s) 
(string-match "ece" s) 
(string-match "ede" s) 
(string-match "eee" s) 
(string-match "efe" s) 
(string-match "ege" s) 
(string-match "ehe" s) 
(string-match "eie" s) 
(string-match "eje" s) 
(string-match "eke" s) 
(string-match "ele" s) 
(string-match "eme" s) 
(string-match "ene" s) 
(string-match "eoe" s) 
(string-match "epe" s) 
(string-match "eqe" s) 
(string-match "ere" s) 
(string-match "ese" s) 
(string-match "ete" s) 
(string-match "eue" s) 
(string-match "eve" s) 
(string-match "ewe" s) 
(string-match "exe" s) 
(string-match "eye" s) 
(string-match "eze" s) 
(string-match "faf" s) 
(string-match "fbf" s) 
(string-match "fcf" s) 
(string-match "fdf" s) 
(string-match "fef" s) 
(string-match "fff" s) 
(string-match "fgf" s) 
(string-match "fhf" s) 
(string-match "fif" s) 
(string-match "fjf" s) 
(string-match "fkf" s) 
(string-match "flf" s) 
(string-match "fmf" s) 
(string-match "fnf" s) 
(string-match "fof" s) 
(string-match "fpf" s) 
(string-match "fqf" s) 
(string-match "frf" s) 
(string-match "fsf" s) 
(string-match "ftf" s) 
(string-match "fuf" s) 
(string-match "fvf" s) 
(string-match "fwf" s) 
(string-match "fxf" s) 
(string-match "fyf" s) 
(string-match "fzf" s) 
(string-match "gag" s) 
(string-match "gbg" s) 
(string-match "gcg" s) 
(string-match "gdg" s) 
(string-match "geg" s) 
(string-match "gfg" s) 
(string-match "ggg" s) 
(string-match "ghg" s) 
(string-match "gig" s) 
(string-match "gjg" s) 
(string-match "gkg" s) 
(string-match "glg" s) 
(string-match "gmg" s) 
(string-match "gng" s) 
(string-match "gog" s) 
(string-match "gpg" s) 
(string-match "gqg" s) 
(string-match "grg" s) 
(string-match "gsg" s) 
(string-match "gtg" s) 
(string-match "gug" s) 
(string-match "gvg" s) 
(string-match "gwg" s) 
(string-match "gxg" s) 
(string-match "gyg" s) 
(string-match "gzg" s) 
(string-match "hah" s) 
(string-match "hbh" s) 
(string-match "hch" s) 
(string-match "hdh" s) 
(string-match "heh" s) 
(string-match "hfh" s) 
(string-match "hgh" s) 
(string-match "hhh" s) 
(string-match "hih" s) 
(string-match "hjh" s) 
(string-match "hkh" s) 
(string-match "hlh" s) 
(string-match "hmh" s) 
(string-match "hnh" s) 
(string-match "hoh" s) 
(string-match "hph" s) 
(string-match "hqh" s) 
(string-match "hrh" s) 
(string-match "hsh" s) 
(string-match "hth" s) 
(string-match "huh" s) 
(string-match "hvh" s) 
(string-match "hwh" s) 
(string-match "hxh" s) 
(string-match "hyh" s) 
(string-match "hzh" s) 
(string-match "iai" s) 
(string-match "ibi" s) 
(string-match "ici" s) 
(string-match "idi" s) 
(string-match "iei" s) 
(string-match "ifi" s) 
(string-match "igi" s) 
(string-match "ihi" s) 
(string-match "iii" s) 
(string-match "iji" s) 
(string-match "iki" s) 
(string-match "ili" s) 
(string-match "imi" s) 
(string-match "ini" s) 
(string-match "ioi" s) 
(string-match "ipi" s) 
(string-match "iqi" s) 
(string-match "iri" s) 
(string-match "isi" s) 
(string-match "iti" s) 
(string-match "iui" s) 
(string-match "ivi" s) 
(string-match "iwi" s) 
(string-match "ixi" s) 
(string-match "iyi" s) 
(string-match "izi" s) 
(string-match "jaj" s) 
(string-match "jbj" s) 
(string-match "jcj" s) 
(string-match "jdj" s) 
(string-match "jej" s) 
(string-match "jfj" s) 
(string-match "jgj" s) 
(string-match "jhj" s) 
(string-match "jij" s) 
(string-match "jjj" s) 
(string-match "jkj" s) 
(string-match "jlj" s) 
(string-match "jmj" s) 
(string-match "jnj" s) 
(string-match "joj" s) 
(string-match "jpj" s) 
(string-match "jqj" s) 
(string-match "jrj" s) 
(string-match "jsj" s) 
(string-match "jtj" s) 
(string-match "juj" s) 
(string-match "jvj" s) 
(string-match "jwj" s) 
(string-match "jxj" s) 
(string-match "jyj" s) 
(string-match "jzj" s) 
(string-match "kak" s) 
(string-match "kbk" s) 
(string-match "kck" s) 
(string-match "kdk" s) 
(string-match "kek" s) 
(string-match "kfk" s) 
(string-match "kgk" s) 
(string-match "khk" s) 
(string-match "kik" s) 
(string-match "kjk" s) 
(string-match "kkk" s) 
(string-match "klk" s) 
(string-match "kmk" s) 
(string-match "knk" s) 
(string-match "kok" s) 
(string-match "kpk" s) 
(string-match "kqk" s) 
(string-match "krk" s) 
(string-match "ksk" s) 
(string-match "ktk" s) 
(string-match "kuk" s) 
(string-match "kvk" s) 
(string-match "kwk" s) 
(string-match "kxk" s) 
(string-match "kyk" s) 
(string-match "kzk" s) 
(string-match "lal" s) 
(string-match "lbl" s) 
(string-match "lcl" s) 
(string-match "ldl" s) 
(string-match "lel" s) 
(string-match "lfl" s) 
(string-match "lgl" s) 
(string-match "lhl" s) 
(string-match "lil" s) 
(string-match "ljl" s) 
(string-match "lkl" s) 
(string-match "lll" s) 
(string-match "lml" s) 
(string-match "lnl" s) 
(string-match "lol" s) 
(string-match "lpl" s) 
(string-match "lql" s) 
(string-match "lrl" s) 
(string-match "lsl" s) 
(string-match "ltl" s) 
(string-match "lul" s) 
(string-match "lvl" s) 
(string-match "lwl" s) 
(string-match "lxl" s) 
(string-match "lyl" s) 
(string-match "lzl" s) 
(string-match "mam" s) 
(string-match "mbm" s) 
(string-match "mcm" s) 
(string-match "mdm" s) 
(string-match "mem" s) 
(string-match "mfm" s) 
(string-match "mgm" s) 
(string-match "mhm" s) 
(string-match "mim" s) 
(string-match "mjm" s) 
(string-match "mkm" s) 
(string-match "mlm" s) 
(string-match "mmm" s) 
(string-match "mnm" s) 
(string-match "mom" s) 
(string-match "mpm" s) 
(string-match "mqm" s) 
(string-match "mrm" s) 
(string-match "msm" s) 
(string-match "mtm" s) 
(string-match "mum" s) 
(string-match "mvm" s) 
(string-match "mwm" s) 
(string-match "mxm" s) 
(string-match "mym" s) 
(string-match "mzm" s) 
(string-match "nan" s) 
(string-match "nbn" s) 
(string-match "ncn" s) 
(string-match "ndn" s) 
(string-match "nen" s) 
(string-match "nfn" s) 
(string-match "ngn" s) 
(string-match "nhn" s) 
(string-match "nin" s) 
(string-match "njn" s) 
(string-match "nkn" s) 
(string-match "nln" s) 
(string-match "nmn" s) 
(string-match "nnn" s) 
(string-match "non" s) 
(string-match "npn" s) 
(string-match "nqn" s) 
(string-match "nrn" s) 
(string-match "nsn" s) 
(string-match "ntn" s) 
(string-match "nun" s) 
(string-match "nvn" s) 
(string-match "nwn" s) 
(string-match "nxn" s) 
(string-match "nyn" s) 
(string-match "nzn" s) 
(string-match "oao" s) 
(string-match "obo" s) 
(string-match "oco" s) 
(string-match "odo" s) 
(string-match "oeo" s) 
(string-match "ofo" s) 
(string-match "ogo" s) 
(string-match "oho" s) 
(string-match "oio" s) 
(string-match "ojo" s) 
(string-match "oko" s) 
(string-match "olo" s) 
(string-match "omo" s) 
(string-match "ono" s) 
(string-match "ooo" s) 
(string-match "opo" s) 
(string-match "oqo" s) 
(string-match "oro" s) 
(string-match "oso" s) 
(string-match "oto" s) 
(string-match "ouo" s) 
(string-match "ovo" s) 
(string-match "owo" s) 
(string-match "oxo" s) 
(string-match "oyo" s) 
(string-match "ozo" s) 
(string-match "pap" s) 
(string-match "pbp" s) 
(string-match "pcp" s) 
(string-match "pdp" s) 
(string-match "pep" s) 
(string-match "pfp" s) 
(string-match "pgp" s) 
(string-match "php" s) 
(string-match "pip" s) 
(string-match "pjp" s) 
(string-match "pkp" s) 
(string-match "plp" s) 
(string-match "pmp" s) 
(string-match "pnp" s) 
(string-match "pop" s) 
(string-match "ppp" s) 
(string-match "pqp" s) 
(string-match "prp" s) 
(string-match "psp" s) 
(string-match "ptp" s) 
(string-match "pup" s) 
(string-match "pvp" s) 
(string-match "pwp" s) 
(string-match "pxp" s) 
(string-match "pyp" s) 
(string-match "pzp" s) 
(string-match "qaq" s) 
(string-match "qbq" s) 
(string-match "qcq" s) 
(string-match "qdq" s) 
(string-match "qeq" s) 
(string-match "qfq" s) 
(string-match "qgq" s) 
(string-match "qhq" s) 
(string-match "qiq" s) 
(string-match "qjq" s) 
(string-match "qkq" s) 
(string-match "qlq" s) 
(string-match "qmq" s) 
(string-match "qnq" s) 
(string-match "qoq" s) 
(string-match "qpq" s) 
(string-match "qqq" s) 
(string-match "qrq" s) 
(string-match "qsq" s) 
(string-match "qtq" s) 
(string-match "quq" s) 
(string-match "qvq" s) 
(string-match "qwq" s) 
(string-match "qxq" s) 
(string-match "qyq" s) 
(string-match "qzq" s) 
(string-match "rar" s) 
(string-match "rbr" s) 
(string-match "rcr" s) 
(string-match "rdr" s) 
(string-match "rer" s) 
(string-match "rfr" s) 
(string-match "rgr" s) 
(string-match "rhr" s) 
(string-match "rir" s) 
(string-match "rjr" s) 
(string-match "rkr" s) 
(string-match "rlr" s) 
(string-match "rmr" s) 
(string-match "rnr" s) 
(string-match "ror" s) 
(string-match "rpr" s) 
(string-match "rqr" s) 
(string-match "rrr" s) 
(string-match "rsr" s) 
(string-match "rtr" s) 
(string-match "rur" s) 
(string-match "rvr" s) 
(string-match "rwr" s) 
(string-match "rxr" s) 
(string-match "ryr" s) 
(string-match "rzr" s) 
(string-match "sas" s) 
(string-match "sbs" s) 
(string-match "scs" s) 
(string-match "sds" s) 
(string-match "ses" s) 
(string-match "sfs" s) 
(string-match "sgs" s) 
(string-match "shs" s) 
(string-match "sis" s) 
(string-match "sjs" s) 
(string-match "sks" s) 
(string-match "sls" s) 
(string-match "sms" s) 
(string-match "sns" s) 
(string-match "sos" s) 
(string-match "sps" s) 
(string-match "sqs" s) 
(string-match "srs" s) 
(string-match "sss" s) 
(string-match "sts" s) 
(string-match "sus" s) 
(string-match "svs" s) 
(string-match "sws" s) 
(string-match "sxs" s) 
(string-match "sys" s) 
(string-match "szs" s) 
(string-match "tat" s) 
(string-match "tbt" s) 
(string-match "tct" s) 
(string-match "tdt" s) 
(string-match "tet" s) 
(string-match "tft" s) 
(string-match "tgt" s) 
(string-match "tht" s) 
(string-match "tit" s) 
(string-match "tjt" s) 
(string-match "tkt" s) 
(string-match "tlt" s) 
(string-match "tmt" s) 
(string-match "tnt" s) 
(string-match "tot" s) 
(string-match "tpt" s) 
(string-match "tqt" s) 
(string-match "trt" s) 
(string-match "tst" s) 
(string-match "ttt" s) 
(string-match "tut" s) 
(string-match "tvt" s) 
(string-match "twt" s) 
(string-match "txt" s) 
(string-match "tyt" s) 
(string-match "tzt" s) 
(string-match "uau" s) 
(string-match "ubu" s) 
(string-match "ucu" s) 
(string-match "udu" s) 
(string-match "ueu" s) 
(string-match "ufu" s) 
(string-match "ugu" s) 
(string-match "uhu" s) 
(string-match "uiu" s) 
(string-match "uju" s) 
(string-match "uku" s) 
(string-match "ulu" s) 
(string-match "umu" s) 
(string-match "unu" s) 
(string-match "uou" s) 
(string-match "upu" s) 
(string-match "uqu" s) 
(string-match "uru" s) 
(string-match "usu" s) 
(string-match "utu" s) 
(string-match "uuu" s) 
(string-match "uvu" s) 
(string-match "uwu" s) 
(string-match "uxu" s) 
(string-match "uyu" s) 
(string-match "uzu" s) 
(string-match "vav" s) 
(string-match "vbv" s) 
(string-match "vcv" s) 
(string-match "vdv" s) 
(string-match "vev" s) 
(string-match "vfv" s) 
(string-match "vgv" s) 
(string-match "vhv" s) 
(string-match "viv" s) 
(string-match "vjv" s) 
(string-match "vkv" s) 
(string-match "vlv" s) 
(string-match "vmv" s) 
(string-match "vnv" s) 
(string-match "vov" s) 
(string-match "vpv" s) 
(string-match "vqv" s) 
(string-match "vrv" s) 
(string-match "vsv" s) 
(string-match "vtv" s) 
(string-match "vuv" s) 
(string-match "vvv" s) 
(string-match "vwv" s) 
(string-match "vxv" s) 
(string-match "vyv" s) 
(string-match "vzv" s) 
(string-match "waw" s) 
(string-match "wbw" s) 
(string-match "wcw" s) 
(string-match "wdw" s) 
(string-match "wew" s) 
(string-match "wfw" s) 
(string-match "wgw" s) 
(string-match "whw" s) 
(string-match "wiw" s) 
(string-match "wjw" s) 
(string-match "wkw" s) 
(string-match "wlw" s) 
(string-match "wmw" s) 
(string-match "wnw" s) 
(string-match "wow" s) 
(string-match "wpw" s) 
(string-match "wqw" s) 
(string-match "wrw" s) 
(string-match "wsw" s) 
(string-match "wtw" s) 
(string-match "wuw" s) 
(string-match "wvw" s) 
(string-match "www" s) 
(string-match "wxw" s) 
(string-match "wyw" s) 
(string-match "wzw" s) 
(string-match "xax" s) 
(string-match "xbx" s) 
(string-match "xcx" s) 
(string-match "xdx" s) 
(string-match "xex" s) 
(string-match "xfx" s) 
(string-match "xgx" s) 
(string-match "xhx" s) 
(string-match "xix" s) 
(string-match "xjx" s) 
(string-match "xkx" s) 
(string-match "xlx" s) 
(string-match "xmx" s) 
(string-match "xnx" s) 
(string-match "xox" s) 
(string-match "xpx" s) 
(string-match "xqx" s) 
(string-match "xrx" s) 
(string-match "xsx" s) 
(string-match "xtx" s) 
(string-match "xux" s) 
(string-match "xvx" s) 
(string-match "xwx" s) 
(string-match "xxx" s) 
(string-match "xyx" s) 
(string-match "xzx" s) 
(string-match "yay" s) 
(string-match "yby" s) 
(string-match "ycy" s) 
(string-match "ydy" s) 
(string-match "yey" s) 
(string-match "yfy" s) 
(string-match "ygy" s) 
(string-match "yhy" s) 
(string-match "yiy" s) 
(string-match "yjy" s) 
(string-match "yky" s) 
(string-match "yly" s) 
(string-match "ymy" s) 
(string-match "yny" s) 
(string-match "yoy" s) 
(string-match "ypy" s) 
(string-match "yqy" s) 
(string-match "yry" s) 
(string-match "ysy" s) 
(string-match "yty" s) 
(string-match "yuy" s) 
(string-match "yvy" s) 
(string-match "ywy" s) 
(string-match "yxy" s) 
(string-match "yyy" s) 
(string-match "yzy" s) 
(string-match "zaz" s) 
(string-match "zbz" s) 
(string-match "zcz" s) 
(string-match "zdz" s) 
(string-match "zez" s) 
(string-match "zfz" s) 
(string-match "zgz" s) 
(string-match "zhz" s) 
(string-match "ziz" s) 
(string-match "zjz" s) 
(string-match "zkz" s) 
(string-match "zlz" s) 
(string-match "zmz" s) 
(string-match "znz" s) 
(string-match "zoz" s) 
(string-match "zpz" s) 
(string-match "zqz" s) 
(string-match "zrz" s) 
(string-match "zsz" s) 
(string-match "ztz" s) 
(string-match "zuz" s) 
(string-match "zvz" s) 
(string-match "zwz" s) 
(string-match "zxz" s) 
(string-match "zyz" s) 
(string-match "zzz" s)
   ))


(define (nice s)
  (and (pair-repeat s)
       (piggy-middle s)))


(define (foo)
  (let ((score 0))
    (dolist (s input)
	    (assert (string? s))
	    (format #t "str = ~a ~%" s)
	    (when (nice s)
	      (set! score (1+ score))))
    score))


(define (fiz)
  (let* ((s "abcdefghijklmnopqrstuvwxyz")
	 (slen (string-length s)))
    (letrec ((baz (lambda (i)
		    (cond
		     ((< i slen)
		      (let ((ch (string-ref s i)))
			(format #t "(string-match \"~a~a.*~a~a\" s) ~%" ch ch ch ch)
			(baz (+ i 1))))
		     (#t #f)))))
      (baz 0))))

(define (biz)
  (let* ((s "abcdefghijklmnopqrstuvwxyz")
	 (slen (string-length s)))
    (letrec ((baz (lambda (i j)
		    (cond
		     ((>= i slen) #f)
		     ((>= j slen) (baz (+ i 1) 0))
		     ((and (< i slen) (< j slen))
		      (let ((ch (string-ref s i))
			    (ch2 (string-ref s j)))
			(format #t "(string-match \"~a~a~a\" s) ~%" ch ch2 ch)
			(baz i (+ j 1))))
		     (#t #f)))))
      (baz 0 0))))


(define (boz)
  (let* ((s "abcdefghijklmnopqrstuvwxyz")
	 (slen (string-length s)))
    (letrec ((baz (lambda (i j)
		    (cond
		     ((>= i slen) #f)
		     ((>= j slen) (baz (+ i 1) 0))
		     ((and (< i slen) (< j slen))
		      (let ((ch (string-ref s i))
			    (ch2 (string-ref s j)))
			(format #t "(string-match \"~a~a.*~a~a\" s) ~%" ch ch2 ch ch2)
			(baz i (+ j 1))))
		     (#t #f)))))
      (baz 0 0))))




(define (test s)
  (format #t "test : ~a is ~a~%" s (if (not (nice s)) "not nice" "nice")))


(define (test-suite )
  (test "qjhvhtzxzqqjkmpb")

  ;; is nice because is has a pair that appears twice (qj) and a letter that
;; repeats with exactly one letter between them (zxz).

  (test "xxyxx")

  ;; is nice because it has a pair that appears twice and a letter that repeats with one
;; between, even though the letters used by each rule overlap.

  (test "uurcxstgmygtbstg")

  ;; is naughty because it has a pair (tg) but no repeat with a single letter
;; between them.

  (test "ieodomkazucvgmuy")
  ;; is naughty because it has a repeating letter with one between (odo), but
;; no pair that appears twice.

  )




#|

PART I I

Realizing the error of his ways, Santa has switched to a better model of determining whether a
string is naughty or nice. None of the old rules apply, as they are all clearly ridiculous.

Now, a nice string is one with all of the following properties:

It contains a pair of any two letters that appears at least twice in the string without overlapping,
like xyxy (xy) or aabcdefgaa (aa), but not like aaa (aa, but it overlaps).

It contains at least one letter which repeats with exactly one letter between them,
like xyx, abcdefeghi (efe), or even aaa.

For example:

qjhvhtzxzqqjkmpb is nice because is has a pair that appears twice (qj) and a letter that
repeats with exactly one letter between them (zxz).

xxyxx is nice because it has a pair that appears twice and a letter that repeats with one
between, even though the letters used by each rule overlap.

uurcxstgmygtbstg is naughty because it has a pair (tg) but no repeat with a single letter
between them.

ieodomkazucvgmuy is naughty because it has a repeating letter with one between (odo), but
no pair that appears twice.

How many strings are nice under these new rules?

69

yay !

|#
