


(define symbols
  '(hn h ie l jt gd z bg dp jw jy ic jz jx ac cs d q cq cu gh w jv kj hx kv bf kw hj eq ct ae ad ab y aw ju ik ih if id p be hf ep dv aa cl cx cw cv eh ag bt bs fk kc cm kz am lu lw dm cz bw jf lc la en al ee ec ds ev im r ar dx dt dw iq bh hy cr cp cj lr gs du da lo aj ew he br bq fl jg ky kx aq lp cy bd bc lv jl ir lt bj ji jh gv gk dh ga fz fo jr je jd ka ak x ex ei do dn lk ba v fw f e gi ch hp ho hm li dl dk dc gu gt gr gy ki hr fi kk fh dr dq ib fd kp kn km ek ej kf iy ix cg ca c gl ig gc gb fp hb ha bb az at fr fq cf hd gz ja iz a lx eg ef dz dj ez ey lb kh ia hz m k ln fg db ay lh bl as ai ah af in il bm bi cb bz ce bk le ld ap an ao er dy ht hs hq gm hw hu hv jc jb iv ft gx gw bp bn cd cc ij ii iw jo lm ll lj fv fu fs gq gn ck ci j i g jk jj es eo io js jq jp co cn kg jm hh hg ke kd kb gp go de fb fm fy fx kq ko ma lz ly u s t fn fj ff fe em el ip di dg fc fa df dd lg ax av au hl hk hi ks kr kl ed eb ea ku kt gg ge gf o n b it is by bx eu et hc gj bv bu bo jn iu ls lq lf))

;; map over symbols use (define <sym> #f)

;; each symbol has an assigned index
(define store (make-array #f (length symbols)))

;; number of unknown symbol outputs
(define unknown (length symbols))


;; extended 16 bit
(define (ex16b xs n)
  (cond
   ((<= n 0) xs)
   (#t (ex16b (cons 0 xs) (- n 1)))))

(define (ex16 xs)  
  (let ((len (length xs)))
    (ex16b xs (- 16 len))))


;; MSB first ... LSB 
(define (dec->bin2 d rs)
  (cond
   ((zero? d) rs)
   (#t (dec->bin2 (floor (/ d 2)) (cons (remainder d 2) rs)))))

(define (dec->bin d)
  (ex16 (dec->bin2 d '())))

;; LSB first ... MSB
(define (bin->dec2 xs p pwr)
  (cond
   ((null? xs) p)
   (#t (bin->dec2 (cdr xs) (+ p (* (car xs) pwr)) (* pwr 2)))))

(define (bin->dec xs)
  (bin->dec2 (reverse xs) 0 1))

(define (or16 xs ys)
  (cond
   ((null? xs) '())
   (#t (let ((a (car xs))
	     (b (car ys)))
	 (cond
	  ((= a 1) (cons 1 (or16 (cdr xs) (cdr ys))))
	  ((= b 1) (cons 1 (or16 (cdr xs) (cdr ys))))
	  (#t (cons 0 (or16 (cdr xs) (cdr ys)))))))))

(define (not16 xs)
  (cond
   ((null? xs) '())
   (#t (let ((a (car xs)))
	 (cond
	  ((= a 1) (cons 0 (not16 (cdr xs))))
	  (#t (cons 1 (not16 (cdr xs)))))))))

(define (and16 xs ys)
  (cond
   ((null? xs) '())
   (#t (let ((a (car xs))
	     (b (car ys)))
	 (cond
	  ((and (= a 1) (= b 1)) (cons 1 (and16 (cdr xs) (cdr ys))))
	  (#t (cons 0 (and16 (cdr xs) (cdr ys)))))))))

(define (shift16-l xs n)
  (cond
   ((<= n 0) xs)
   (#t (shift16-l (append (cdr xs) (list 0)) (- n 1)))))

(define (take2 xs ys n)
  (cond
   ((< n 1) (reverse ys))
   (#t (take2 (cdr xs) (cons (car xs) ys)(- n 1)))))

(define (take xs n)
  (take2 xs '() n))

(define (shift16-r xs n)
  (cond
   ((<= n 0) xs)
   (#t
    (shift16-r (cons 0 (take xs 15)) (- n 1)))))


(define (loop)
  (begin 
    (let ((a (array-ref store 93)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 269))))
    (let ((a (array-ref store 0)))
      (when a (array-set! store (not16 a) 137)))
    (let ((a (array-ref store 1)))
      (when a (array-set! store (not16 a) 255)))
    (let ((a (array-ref store 43))
	  (b (array-ref store 306)))
      (when (and a b) (array-set! store (and16 a b) 0)))
    (let ((a (array-ref store 34))
	  (b (array-ref store 31)))
      (when (and a b)
	(array-set! store (or16 a b) 207)))
    (let ((a (array-ref store 123)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 6))))
    (let ((a (array-ref store 133))
	  (b (array-ref store 132)))
      (when (and a b) (array-set! store (and16 a b) 1)))
    (let ((a (array-ref store 2)))
      (when a (array-set! store (not16 a) 39)))
    (let ((a (array-ref store 117))
	  (b (array-ref store 116)))
      (when (and a b)
	(array-set! store (and16 a b) 170)))
    (let ((a (array-ref store 34))
	  (b (array-ref store 31)))
      (when (and a b)
	(array-set! store (and16 a b) 52)))
    (let ((b (array-ref store 5)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 318))))
    (let ((a (array-ref store 3)))
      (when a (array-set! store (not16 a) 196)))
    (let ((a (array-ref store 301))
	  (b (array-ref store 126)))
      (when (and a b)
	(array-set! store (and16 a b) 153)))
    (let ((a (array-ref store 42))
	  (b (array-ref store 7)))
      (when (and a b)
	(array-set! store (and16 a b) 81)))
    (let ((a (array-ref store 204)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 305))))
    (let ((a (array-ref store 154))
	  (b (array-ref store 11)))
      (when (and a b) (array-set! store (and16 a b) 2)))
    (let ((a (array-ref store 16))
	  (b (array-ref store 254)))
      (when (and a b) (array-set! store (and16 a b) 3)))
    (let ((a (array-ref store 301))
	  (b (array-ref store 126)))
      (when (and a b) (array-set! store (or16 a b) 8)))
    (let ((a (array-ref store 194))
	  (b (array-ref store 168)))
      (when (and a b) (array-set! store (or16 a b) 38)))
    (let ((a (array-ref store 18))
	  (b (array-ref store 15)))
      (when (and a b)
	(array-set! store (and16 a b) 30)))
    (let ((a (array-ref store 178))
	  (b (array-ref store 177)))
      (when (and a b)
	(array-set! store (or16 a b) 249)))
    (let ((a (array-ref store 154))
	  (b (array-ref store 11)))
      (when (and a b) (array-set! store (or16 a b) 40)))
    (let ((a (array-ref store 43))
	  (b (array-ref store 306)))
      (when (and a b)
	(array-set! store (or16 a b) 138)))
    (let ((a (array-ref store 172)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 229))))
    (let ((a (array-ref store 118))
	  (b (array-ref store 262)))
      (when (and a b) (array-set! store (or16 a b) 4)))
    (let ((a (array-ref store 6))
	  (b (array-ref store 46)))
      (when (and a b)
	(array-set! store (and16 a b) 14)))
    (let ((a (array-ref store 4))
	  (b (array-ref store 22)))
      (when (and a b) (array-set! store (and16 a b) 9)))
    (let ((a (array-ref store 195))
	  (b (array-ref store 37)))
      (when (and a b)
	(array-set! store (and16 a b) 74)))
    (let ((a (array-ref store 115))
	  (b (array-ref store 169)))
      (when (and a b) (array-set! store (and16 a b) 5)))
    (let ((a (array-ref store 6))
	  (b (array-ref store 46)))
      (when (and a b) (array-set! store (or16 a b) 33)))
    (let ((a (array-ref store 26)))
      (when a (array-set! store (not16 a) 7)))
    (let ((a (array-ref store 305))
	  (b (array-ref store 304)))
      (when (and a b) (array-set! store (or16 a b) 35)))
    (let ((a (array-ref store 263))
	  (b (array-ref store 9)))
      (when (and a b)
	(array-set! store (and16 a b) 10)))
    (let ((a (array-ref store 8))
	  (b (array-ref store 152)))
      (when (and a b)
	(array-set! store (and16 a b) 72)))
    (let ((a (array-ref store 114))
	  (b (array-ref store 189)))
      (when (and a b)
	(array-set! store (and16 a b) 141)))
    (let ((a (array-ref store 67)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 216))))
    (let ((a (array-ref store 130))
	  (b (array-ref store 21)))
      (when (and a b)
	(array-set! store (or16 a b) 123)))
    (let ((a (array-ref store 263))
	  (b (array-ref store 9)))
      (when (and a b) (array-set! store (or16 a b) 13)))
    (let ((a (array-ref store 270))
	  (b (array-ref store 269)))
      (when (and a b)
	(array-set! store (and16 a b) 28)))
    (let ((a (array-ref store 253))
	  (b (array-ref store 30)))
      (when (and a b) (array-set! store (or16 a b) 19)))
    (let ((b (array-ref store 59)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 219))))
    (let ((a (array-ref store 10)))
      (when a (array-set! store (not16 a) 12)))
    (let ((a (array-ref store 204)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 176))))
    (let ((a (array-ref store 195)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 11))))
    (let ((a (array-ref store 150)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 217))))
    (let ((a (array-ref store 20))
	  (b (array-ref store 134)))
      (when (and a b)
	(array-set! store (or16 a b) 330)))
    (let ((a (array-ref store 13))
	  (b (array-ref store 12)))
      (when (and a b)
	(array-set! store (and16 a b) 121)))
    (let ((a (array-ref store 195))
	  (b (array-ref store 37)))
      (when (and a b)
	(array-set! store (or16 a b) 209)))
    (let ((a (array-ref store 117)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 177))))
    (let ((a (array-ref store 14)))
      (when a (array-set! store (not16 a) 32)))
    (let ((a (array-ref store 161)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 23))))
    (let ((a (array-ref store 88))
	  (b (array-ref store 78)))
      (when (and a b) (array-set! store (or16 a b) 45)))
    (let ((a (array-ref store 83)))
      (when a (array-set! store (not16 a) 15)))
    (let ((a (array-ref store 41)))
      (when a (array-set! store (not16 a) 17)))
    (let ((a (array-ref store 16))
	  (b (array-ref store 254)))
      (when (and a b)
	(array-set! store (or16 a b) 197)))
    (let ((a (array-ref store 322)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 133))))
    (let ((a (array-ref store 309))
	  (b (array-ref store 315)))
      (when (and a b)
	(array-set! store (and16 a b) 25)))
    (let ((a (array-ref store 322)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 16))))
    (let ((a (array-ref store 301)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 297))))
    (let ((a (array-ref store 320))
	  (b (array-ref store 17)))
      (when (and a b)
	(array-set! store (and16 a b) 75)))
    (let ((a (array-ref store 85))
	  (b (array-ref store 84)))
      (when (and a b) (array-set! store (or16 a b) 18)))
    (let ((a (array-ref store 253)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 85))))
    (let ((a (array-ref store 80))
	  (b (array-ref store 295)))
      (when (and a b)
	(array-set! store (or16 a b) 107)))
    (let ((a (array-ref store 311))
	  (b (array-ref store 310)))
      (when (and a b)
	(array-set! store (and16 a b) 316)))
    (let ((a (array-ref store 322)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 132))))
    (let ((a (array-ref store 19))
	  (b (array-ref store 49)))
      (when (and a b)
	(array-set! store (and16 a b) 48)))
    (let ((b (array-ref store 223)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 228))))
    (let ((a (array-ref store 312)))
      (when a (array-set! store (not16 a) 70)))
    (let ((a (array-ref store 237)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 95))))
    (let ((a (array-ref store 150))
	  (b (array-ref store 25)))
      (when (and a b) (array-set! store (or16 a b) 27)))
    (let ((a (array-ref store 117)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 20))))
    (let ((a (array-ref store 287)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 21))))
    (let ((a (array-ref store 314))
	  (b (array-ref store 313)))
      (when (and a b) (array-set! store (or16 a b) 71)))
    (let ((a (array-ref store 24))
	  (b (array-ref store 82)))
      (when (and a b)
	(array-set! store (or16 a b) 195)))
    (let ((a (array-ref store 51)))
      (when a (array-set! store (not16 a) 125)))
    (let ((a (array-ref store 150)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 157))))
    (let ((a (array-ref store 159))
	  (b (array-ref store 293)))
      (when (and a b)
	(array-set! store (and16 a b) 68)))
    (let ((a (array-ref store 36)))
      (when a (array-set! store (not16 a) 22)))
    (let ((a (array-ref store 147))
	  (b (array-ref store 23)))
      (when (and a b)
	(array-set! store (or16 a b) 150)))
    (let ((a (array-ref store 93)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 24))))
    (let ((a (array-ref store 44))
	  (b (array-ref store 260)))
      (when (and a b) (array-set! store (or16 a b) 29)))
    (let ((a (array-ref store 150))
	  (b (array-ref store 25)))
      (when (and a b)
	(array-set! store (and16 a b) 99)))
    (let ((a (array-ref store 94))
	  (b (array-ref store 53)))
      (when (and a b)
	(array-set! store (and16 a b) 332)))
    (let ((a (array-ref store 79))
	  (b (array-ref store 77)))
      (when (and a b)
	(array-set! store (or16 a b) 222)))
    (let ((a (array-ref store 204))
	  (b (array-ref store 103)))
      (when (and a b)
	(array-set! store (and16 a b) 26)))
    (let ((a (array-ref store 27))
	  (b (array-ref store 98)))
      (when (and a b)
	(array-set! store (and16 a b) 58)))
    (let ((a (array-ref store 28)))
      (when a (array-set! store (not16 a) 307)))
    (let ((a (array-ref store 174)))
      (when a (array-set! store (not16 a) 104)))
    (let ((a (array-ref store 286)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 220))))
    (let ((a (array-ref store 330)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 167))))
    (let ((a (array-ref store 29)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 55))))
    (let ((a (array-ref store 253))
	  (b (array-ref store 30)))
      (when (and a b)
	(array-set! store (and16 a b) 50)))
    (let ((a (array-ref store 291))
	  (b (array-ref store 151)))
      (when (and a b)
	(array-set! store (and16 a b) 149)))
    (let ((a (array-ref store 33))
	  (b (array-ref store 32)))
      (when (and a b)
	(array-set! store (and16 a b) 31)))
    (let ((a (array-ref store 123)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 34))))
    (let ((a (array-ref store 35))
	  (b (array-ref store 201)))
      (when (and a b)
	(array-set! store (and16 a b) 175)))
    (let ((a (array-ref store 87)))
      (when a (array-set! store (not16 a) 144)))
    (let ((b (array-ref store 271)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 161))))
    (let ((a (array-ref store 195)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 324))))
    (let ((a (array-ref store 253)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 47))))
    (let ((a (array-ref store 118))
	  (b (array-ref store 262)))
      (when (and a b)
	(array-set! store (and16 a b) 36)))
    (let ((a (array-ref store 38))
	  (b (array-ref store 240)))
      (when (and a b)
	(array-set! store (and16 a b) 37)))
    (let ((a (array-ref store 40))
	  (b (array-ref store 39)))
      (when (and a b)
	(array-set! store (and16 a b) 168)))
    (let ((a (array-ref store 158))
	  (b (array-ref store 157)))
      (when (and a b)
	(array-set! store (or16 a b) 282)))
    (let ((a (array-ref store 66)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 61))))
    (let ((a (array-ref store 56)))
      (when a (array-set! store (not16 a) 272)))
    (let ((a (array-ref store 322))
	  (b (array-ref store 321)))
      (when (and a b)
	(array-set! store (and16 a b) 41)))
    (let ((a (array-ref store 150)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 158))))
    (let ((b (array-ref store 60)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 105))))
    (let ((a (array-ref store 73))
	  (b (array-ref store 92)))
      (when (and a b)
	(array-set! store (and16 a b) 191)))
    (let ((a (array-ref store 93))
	  (b (array-ref store 136)))
      (when (and a b)
	(array-set! store (and16 a b) 148)))
    (let ((a (array-ref store 204))
	  (b (array-ref store 103)))
      (when (and a b) (array-set! store (or16 a b) 42)))
    (let ((a (array-ref store 236))
	  (b (array-ref store 95)))
      (when (and a b)
	(array-set! store (and16 a b) 54)))
    (let ((a (array-ref store 252))
	  (b (array-ref store 47)))
      (when (and a b) (array-set! store (or16 a b) 57)))
    (let ((a (array-ref store 64)))
      (when a (array-set! store (not16 a) 326)))
    (let ((a (array-ref store 93)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 43))))
    (let ((a (array-ref store 45)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 44))))
    (let ((a (array-ref store 123)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 46))))
    (let ((a (array-ref store 252))
	  (b (array-ref store 47)))
      (when (and a b)
	(array-set! store (and16 a b) 266)))
    (let ((a (array-ref store 276))
	  (b (array-ref store 141)))
      (when (and a b)
	(array-set! store (and16 a b) 62)))
    (let ((b (array-ref store 48)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 102))))
    (let ((a (array-ref store 50)))
      (when a (array-set! store (not16 a) 49)))
    (let ((a (array-ref store 179)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 63))))
    (let ((a (array-ref store 188))
	  (b (array-ref store 187)))
      (when (and a b)
	(array-set! store (and16 a b) 51)))
    (let ((a (array-ref store 52)))
      (when a (array-set! store (not16 a) 206)))
    (let ((a (array-ref store 54)))
      (when a (array-set! store (not16 a) 53)))
    (let ((a (array-ref store 222)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 314))))
    (let ((a (array-ref store 55))
	  (b (array-ref store 290)))
      (when (and a b) (array-set! store (or16 a b) 96)))
    (let ((a (array-ref store 264))
	  (b (array-ref store 121)))
      (when (and a b)
	(array-set! store (and16 a b) 56)))
    (let ((a (array-ref store 73))
	  (b (array-ref store 92)))
      (when (and a b)
	(array-set! store (or16 a b) 124)))
    (let ((a (array-ref store 112))
	  (b (array-ref store 234)))
      (when (and a b)
	(array-set! store (and16 a b) 146)))
    (let ((a (array-ref store 57))
	  (b (array-ref store 265)))
      (when (and a b)
	(array-set! store (and16 a b) 84)))
    (let ((a (array-ref store 230))
	  (b (array-ref store 119)))
      (when (and a b)
	(array-set! store (and16 a b) 65)))
    (let ((a (array-ref store 222)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 313))))
    (let ((b (array-ref store 58)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 67))))
    (let ((a (array-ref store 91))
	  (b (array-ref store 69)))
      (when (and a b)
	(array-set! store (and16 a b) 59)))
    (let ((a (array-ref store 93)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 270))))
    (let ((a (array-ref store 278))
	  (b (array-ref store 289)))
      (when (and a b)
	(array-set! store (or16 a b) 117)))
    (let ((a (array-ref store 86))
	  (b (array-ref store 108)))
      (when (and a b)
	(array-set! store (and16 a b) 60)))
    (let ((a (array-ref store 317)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 173))))
    (let ((a (array-ref store 61))
	  (b (array-ref store 105)))
      (when (and a b)
	(array-set! store (or16 a b) 185)))
    (let ((a (array-ref store 62)))
      (when a (array-set! store (not16 a) 127)))
    (let ((a (array-ref store 335))
	  (b (array-ref store 65)))
      (when (and a b) (array-set! store (or16 a b) 97)))
    (let ((a (array-ref store 338)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 285))))
    (let ((a (array-ref store 242))
	  (b (array-ref store 163)))
      (when (and a b)
	(array-set! store (and16 a b) 183)))
    (let ((a (array-ref store 232))
	  (b (array-ref store 231)))
      (when (and a b)
	(array-set! store (and16 a b) 120)))
    (let ((a (array-ref store 63))
	  (b (array-ref store 102)))
      (when (and a b) (array-set! store (or16 a b) 89)))
    (let ((a (array-ref store 333))
	  (b (array-ref store 332)))
      (when (and a b)
	(array-set! store (and16 a b) 64)))
    (let ((a (array-ref store 335)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 163))))
    (let ((a (array-ref store 335))
	  (b (array-ref store 65)))
      (when (and a b)
	(array-set! store (and16 a b) 111)))
    (let ((a (array-ref store 192))
	  (b (array-ref store 67)))
      (when (and a b) (array-set! store (or16 a b) 66)))
    (let ((b (array-ref store 68)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 260))))
    (let ((a (array-ref store 106))
	  (b (array-ref store 257)))
      (when (and a b)
	(array-set! store (or16 a b) 268)))
    (let ((a (array-ref store 122)))
      (when a (array-set! store (not16 a) 69)))
    (let ((a (array-ref store 71))
	  (b (array-ref store 70)))
      (when (and a b)
	(array-set! store (and16 a b) 187)))
    (let ((b (array-ref store 72)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 78))))
    (let ((a (array-ref store 328)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 73))))
    (let ((a (array-ref store 74)))
      (when a (array-set! store (not16 a) 208)))
    (let ((a (array-ref store 131))
	  (b (array-ref store 279)))
      (when (and a b)
	(array-set! store (and16 a b) 116)))
    (let ((b (array-ref store 75)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 287))))
    (let ((a (array-ref store 100))
	  (b (array-ref store 76)))
      (when (and a b)
	(array-set! store (or16 a b) 204)))
    (let ((a (array-ref store 219)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 76))))
    (let ((a (array-ref store 222))
	  (b (array-ref store 160)))
      (when (and a b)
	(array-set! store (and16 a b) 294)))
    (let ((a (array-ref store 78)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 77))))
    (let ((a (array-ref store 301)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 79))))
    (let ((a (array-ref store 227)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 80))))
    (let ((a (array-ref store 90)))
      (when a (array-set! store (not16 a) 101)))
    (let ((a (array-ref store 117)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 178))))
    (let ((b (array-ref store 81)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 211))))
    (let ((a (array-ref store 228)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 82))))
    (let ((a (array-ref store 85))
	  (b (array-ref store 84)))
      (when (and a b)
	(array-set! store (and16 a b) 83)))
    (let ((a (array-ref store 338))
	  (b (array-ref store 337)))
      (when (and a b) (array-set! store (or16 a b) 86)))
    (let ((a (array-ref store 109))
	  (b (array-ref store 211)))
      (when (and a b)
	(array-set! store (or16 a b) 215)))
    (let ((a (array-ref store 113))
	  (b (array-ref store 250)))
      (when (and a b)
	(array-set! store (and16 a b) 87)))
    (let ((a (array-ref store 117)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 171))))
    (let ((a (array-ref store 89)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 88))))
    (let ((a (array-ref store 202))
	  (b (array-ref store 139)))
      (when (and a b)
	(array-set! store (or16 a b) 246)))
    (let ((a (array-ref store 302))
	  (b (array-ref store 244)))
      (when (and a b)
	(array-set! store (and16 a b) 90)))
    (let ((a (array-ref store 329))
	  (b (array-ref store 180)))
      (when (and a b) (array-set! store (or16 a b) 93)))
    (let ((a (array-ref store 123))
	  (b (array-ref store 205)))
      (when (and a b) (array-set! store (or16 a b) 91)))
    (let ((a (array-ref store 167))
	  (b (array-ref store 226)))
      (when (and a b)
	(array-set! store (and16 a b) 275)))
    (let ((a (array-ref store 335)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 232))))
    (let ((a (array-ref store 328)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 92))))
    (let ((a (array-ref store 93))
	  (b (array-ref store 136)))
      (when (and a b)
	(array-set! store (or16 a b) 225)))
    (let ((a (array-ref store 236))
	  (b (array-ref store 95)))
      (when (and a b) (array-set! store (or16 a b) 94)))
    (let ((a (array-ref store 96)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 319))))
    (let ((a (array-ref store 237))
	  (b (array-ref store 325)))
      (when (and a b)
	(array-set! store (or16 a b) 213)))
    (let ((a (array-ref store 97))
	  (b (array-ref store 110)))
      (when (and a b)
	(array-set! store (and16 a b) 258)))
    (let ((a (array-ref store 99)))
      (when a (array-set! store (not16 a) 98)))
    (let ((a (array-ref store 113))
	  (b (array-ref store 250)))
      (when (and a b)
	(array-set! store (or16 a b) 145)))
    (let ((a (array-ref store 123)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 100))))
    (let ((a (array-ref store 198))
	  (b (array-ref store 101)))
      (when (and a b)
	(array-set! store (and16 a b) 337)))
    (let ((a (array-ref store 102)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 142))))
    (let ((a (array-ref store 129))
	  (b (array-ref store 104)))
      (when (and a b)
	(array-set! store (and16 a b) 103)))
    (let ((a (array-ref store 105)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 284))))
    (let ((a (array-ref store 237))
	  (b (array-ref store 325)))
      (when (and a b)
	(array-set! store (and16 a b) 165)))
    (let ((a (array-ref store 107)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 106))))
    (let ((a (array-ref store 336)))
      (when a (array-set! store (not16 a) 108)))
    (let ((a (array-ref store 218)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 109))))
    (let ((a (array-ref store 111)))
      (when a (array-set! store (not16 a) 110)))
    (let ((a (array-ref store 330))
	  (b (array-ref store 143)))
      (when (and a b)
	(array-set! store (or16 a b) 112)))
    (let ((a (array-ref store 330)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 113))))
    (let ((a (array-ref store 300))
	  (b (array-ref store 297)))
      (when (and a b)
	(array-set! store (or16 a b) 114)))
    (let ((a (array-ref store 117))
	  (b (array-ref store 116)))
      (when (and a b)
	(array-set! store (or16 a b) 115)))
    (let ((a (array-ref store 264)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 118))))
    (let ((a (array-ref store 162))
	  (b (array-ref store 182)))
      (when (and a b)
	(array-set! store (and16 a b) 231)))
    (let ((a (array-ref store 120)))
      (when a (array-set! store (not16 a) 119)))
    (let ((a (array-ref store 264))
	  (b (array-ref store 121)))
      (when (and a b)
	(array-set! store (or16 a b) 273)))
    (let ((a (array-ref store 123))
	  (b (array-ref store 205)))
      (when (and a b)
	(array-set! store (and16 a b) 122)))
    (let ((a (array-ref store 128)))
      (when a (array-set! store (not16 a) 245)))
    (let ((a (array-ref store 156)))
      (when a (array-set! store (not16 a) 281)))
    (let ((a (array-ref store 124))
	  (b (array-ref store 190)))
      (when (and a b)
	(array-set! store (and16 a b) 299)))
    (let ((a (array-ref store 186))
	  (b (array-ref store 125)))
      (when (and a b)
	(array-set! store (and16 a b) 160)))
    (let ((a (array-ref store 140))
	  (b (array-ref store 127)))
      (when (and a b)
	(array-set! store (and16 a b) 126)))
    (let ((a (array-ref store 202))
	  (b (array-ref store 139)))
      (when (and a b)
	(array-set! store (and16 a b) 128)))
    (let ((a (array-ref store 237)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 333))))
    (let ((a (array-ref store 176))
	  (b (array-ref store 175)))
      (when (and a b)
	(array-set! store (or16 a b) 129)))
    (let ((a (array-ref store 322)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 130))))
    (let ((a (array-ref store 238)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 135))))
    (let ((a (array-ref store 277))
	  (b (array-ref store 155)))
      (when (and a b)
	(array-set! store (and16 a b) 292)))
    (let ((a (array-ref store 171))
	  (b (array-ref store 247)))
      (when (and a b)
	(array-set! store (or16 a b) 131)))
    (let ((a (array-ref store 133))
	  (b (array-ref store 132)))
      (when (and a b)
	(array-set! store (or16 a b) 256)))
    (let ((a (array-ref store 318)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 134))))
    (let ((a (array-ref store 330))
	  (b (array-ref store 143)))
      (when (and a b)
	(array-set! store (and16 a b) 235)))
    (let ((a (array-ref store 164))
	  (b (array-ref store 135)))
      (when (and a b)
	(array-set! store (or16 a b) 253)))
    (let ((a (array-ref store 138))
	  (b (array-ref store 137)))
      (when (and a b)
	(array-set! store (and16 a b) 136)))
    (let ((a (array-ref store 338)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 139))))
    (let ((a (array-ref store 204)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 304))))
    (let ((a (array-ref store 276))
	  (b (array-ref store 141)))
      (when (and a b)
	(array-set! store (or16 a b) 140)))
    (let ((a (array-ref store 200))
	  (b (array-ref store 142)))
      (when (and a b)
	(array-set! store (or16 a b) 301)))
    (let ((a (array-ref store 145))
	  (b (array-ref store 144)))
      (when (and a b)
	(array-set! store (and16 a b) 143)))
    (let ((b (array-ref store 146)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 181))))
    (let ((a (array-ref store 203))
	  (b (array-ref store 210)))
      (when (and a b)
	(array-set! store (or16 a b) 237)))
    (let ((a (array-ref store 264)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 147))))
    (let ((a (array-ref store 148)))
      (when a (array-set! store (not16 a) 224)))
    (let ((b (array-ref store 149)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 290))))
    (let ((a (array-ref store 150)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 311))))
    (let ((a (array-ref store 222)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 188))))
    (let ((a (array-ref store 199)))
      (when a (array-set! store (not16 a) 151)))
    (let ((a (array-ref store 153)))
      (when a (array-set! store (not16 a) 152)))
    (let ((a (array-ref store 195)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 154))))
    (let ((a (array-ref store 298)))
      (when a (array-set! store (not16 a) 155)))
    (let ((a (array-ref store 158))
	  (b (array-ref store 157)))
      (when (and a b)
	(array-set! store (and16 a b) 156)))
    (let ((a (array-ref store 222))
	  (b (array-ref store 160)))
      (when (and a b)
	(array-set! store (or16 a b) 159)))
    (let ((a (array-ref store 267))
	  (b (array-ref store 161)))
      (when (and a b)
	(array-set! store (or16 a b) 193)))
    (let ((a (array-ref store 242))
	  (b (array-ref store 163)))
      (when (and a b)
	(array-set! store (or16 a b) 162)))
    (let ((a (array-ref store 166)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 288))))
    (let ((a (array-ref store 237)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 164))))
    (let ((a (array-ref store 165)))
      (when a (array-set! store (not16 a) 212)))
    (let ((a (dec->bin 0))) (array-set! store a 166))
    (let ((a (array-ref store 167))
	  (b (array-ref store 226)))
      (when (and a b)
	(array-set! store (or16 a b) 251)))
    (let ((a (array-ref store 194))
	  (b (array-ref store 168)))
      (when (and a b)
	(array-set! store (and16 a b) 241)))
    (let ((a (array-ref store 170)))
      (when a (array-set! store (not16 a) 169)))
    (let ((a (array-ref store 171))
	  (b (array-ref store 247)))
      (when (and a b)
	(array-set! store (and16 a b) 280)))
    (let ((a (array-ref store 173))
	  (b (array-ref store 181)))
      (when (and a b)
	(array-set! store (or16 a b) 172)))
    (let ((a (array-ref store 176))
	  (b (array-ref store 175)))
      (when (and a b)
	(array-set! store (and16 a b) 174)))
    (let ((a (array-ref store 178))
	  (b (array-ref store 177)))
      (when (and a b)
	(array-set! store (and16 a b) 233)))
    (let ((a (array-ref store 214))
	  (b (array-ref store 238)))
      (when (and a b)
	(array-set! store (or16 a b) 179)))
    (let ((a (array-ref store 181)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 180))))
    (let ((a (array-ref store 183)))
      (when a (array-set! store (not16 a) 182)))
    (let ((a (array-ref store 185)))
      (when a (array-set! store a 184)))
    (let ((a (array-ref store 188))
	  (b (array-ref store 187)))
      (when (and a b)
	(array-set! store (or16 a b) 186)))
    (let ((a (array-ref store 296)))
      (when a (array-set! store (not16 a) 189)))
    (let ((a (array-ref store 191)))
      (when a (array-set! store (not16 a) 190)))
    (let ((a (array-ref store 193)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 192))))
    (let ((a (array-ref store 195)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 194))))
    (let ((a (array-ref store 197))
	  (b (array-ref store 196)))
      (when (and a b)
	(array-set! store (and16 a b) 321)))
    (let ((a (array-ref store 302))
	  (b (array-ref store 244)))
      (when (and a b)
	(array-set! store (or16 a b) 198)))
    (let ((a (array-ref store 328))
	  (b (array-ref store 292)))
      (when (and a b)
	(array-set! store (and16 a b) 199)))
    (let ((a (array-ref store 253)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 200))))
    (let ((a (array-ref store 303)))
      (when a (array-set! store (not16 a) 201)))
    (let ((a (array-ref store 221))
	  (b (array-ref store 259)))
      (when (and a b)
	(array-set! store (or16 a b) 328)))
    (let ((a (array-ref store 338)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 202))))
    (let ((a (array-ref store 204)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 203))))
    (let ((a (array-ref store 207))
	  (b (array-ref store 206)))
      (when (and a b)
	(array-set! store (and16 a b) 205)))
    (let ((a (array-ref store 209))
	  (b (array-ref store 208)))
      (when (and a b)
	(array-set! store (and16 a b) 261)))
    (let ((a (array-ref store 211)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 210))))
    (let ((a (array-ref store 213))
	  (b (array-ref store 212)))
      (when (and a b)
	(array-set! store (and16 a b) 239)))
    (let ((a (array-ref store 215)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 214))))
    (let ((a (array-ref store 217))
	  (b (array-ref store 216)))
      (when (and a b)
	(array-set! store (or16 a b) 338)))
    (let ((a (array-ref store 220))
	  (b (array-ref store 219)))
      (when (and a b)
	(array-set! store (or16 a b) 218)))
    (let ((a (array-ref store 222)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 221))))
    (let ((a (array-ref store 225))
	  (b (array-ref store 224)))
      (when (and a b)
	(array-set! store (and16 a b) 223)))
    (let ((a (array-ref store 330)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 226))))
    (let ((a (dec->bin 19138)))
      (array-set! store a 322))
    (let ((a (array-ref store 229))
	  (b (array-ref store 228)))
      (when (and a b)
	(array-set! store (or16 a b) 227)))
    (let ((a (array-ref store 232))
	  (b (array-ref store 231)))
      (when (and a b)
	(array-set! store (or16 a b) 230)))
    (let ((a (array-ref store 334))
	  (b (array-ref store 243)))
      (when (and a b)
	(array-set! store (or16 a b) 264)))
    (let ((a (array-ref store 233)))
      (when a (array-set! store (not16 a) 248)))
    (let ((a (array-ref store 235)))
      (when a (array-set! store (not16 a) 234)))
    (let ((a (array-ref store 237)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 236))))
    (let ((b (array-ref store 239)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 238))))
    (let ((a (array-ref store 241)))
      (when a (array-set! store (not16 a) 240)))
    (let ((a (array-ref store 335)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 242))))
    (let ((a (array-ref store 257)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 243))))
    (let ((a (array-ref store 246))
	  (b (array-ref store 245)))
      (when (and a b)
	(array-set! store (and16 a b) 244)))
    (let ((a (array-ref store 249))
	  (b (array-ref store 248)))
      (when (and a b)
	(array-set! store (and16 a b) 247)))
    (let ((a (array-ref store 251))
	  (b (array-ref store 274)))
      (when (and a b)
	(array-set! store (and16 a b) 250)))
    (let ((a (array-ref store 253)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 252))))
    (let ((a (array-ref store 256))
	  (b (array-ref store 255)))
      (when (and a b)
	(array-set! store (and16 a b) 254)))
    (let ((b (array-ref store 258)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 257))))
    (let ((a (array-ref store 260)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 259))))
    (let ((b (array-ref store 261)))
      (when b
	(let ((a (dec->bin 1)))
          (array-set! store (and16 a b) 295))))
    (let ((a (array-ref store 264)))
      (when a
	(let ((b 5))
          (array-set! store (shift16-r a b) 262))))
    (let ((a (array-ref store 264)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 263))))
    (let ((a (array-ref store 266)))
      (when a (array-set! store (not16 a) 265)))
    (let ((a (array-ref store 268)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-l a b) 267))))
    (let ((a (array-ref store 270))
	  (b (array-ref store 269)))
      (when (and a b)
	(array-set! store (or16 a b) 308)))
    (let ((a (array-ref store 273))
	  (b (array-ref store 272)))
      (when (and a b)
	(array-set! store (and16 a b) 271)))
    (let ((a (array-ref store 275)))
      (when a (array-set! store (not16 a) 274)))
    (let ((a (array-ref store 301)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 276))))
    (let ((a (array-ref store 327))
	  (b (array-ref store 299)))
      (when (and a b)
	(array-set! store (or16 a b) 277)))
    (let ((a (array-ref store 328)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 278))))
    (let ((a (array-ref store 280)))
      (when a (array-set! store (not16 a) 279)))
    (let ((a (array-ref store 282))
	  (b (array-ref store 281)))
      (when (and a b)
	(array-set! store (and16 a b) 310)))
    (let ((a (array-ref store 285))
	  (b (array-ref store 284)))
      (when (and a b)
	(array-set! store (or16 a b) 283)))
    (let ((a (array-ref store 288))
	  (b (array-ref store 287)))
      (when (and a b)
	(array-set! store (or16 a b) 286)))
    (let ((a (array-ref store 290)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 289))))
    (let ((a (array-ref store 328))
	  (b (array-ref store 292)))
      (when (and a b)
	(array-set! store (or16 a b) 291)))
    (let ((a (array-ref store 294)))
      (when a (array-set! store (not16 a) 293)))
    (let ((a (array-ref store 295)))
      (when a
	(let ((b 15))
          (array-set! store (shift16-l a b) 323))))
    (let ((a (array-ref store 300))
	  (b (array-ref store 297)))
      (when (and a b)
	(array-set! store (and16 a b) 296)))
    (let ((a (array-ref store 327))
	  (b (array-ref store 299)))
      (when (and a b)
	(array-set! store (and16 a b) 298)))
    (let ((a (array-ref store 301)))
      (when a
	(let ((b 3))
          (array-set! store (shift16-r a b) 300))))
    (let ((a (array-ref store 338)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 302))))
    (let ((a (array-ref store 305))
	  (b (array-ref store 304)))
      (when (and a b)
	(array-set! store (and16 a b) 303)))
    (let ((a (array-ref store 308))
	  (b (array-ref store 307)))
      (when (and a b)
	(array-set! store (and16 a b) 306)))
    (let ((a (array-ref store 311))
	  (b (array-ref store 310)))
      (when (and a b)
	(array-set! store (or16 a b) 309)))
    (let ((a (array-ref store 314))
	  (b (array-ref store 313)))
      (when (and a b)
	(array-set! store (and16 a b) 312)))
    (let ((a (array-ref store 316)))
      (when a (array-set! store (not16 a) 315)))
    (let ((a (array-ref store 319))
	  (b (array-ref store 318)))
      (when (and a b)
	(array-set! store (or16 a b) 317)))
    (let ((a (array-ref store 322))
	  (b (array-ref store 321)))
      (when (and a b)
	(array-set! store (or16 a b) 320)))
    (let ((a (array-ref store 324))
	  (b (array-ref store 323)))
      (when (and a b)
	(array-set! store (or16 a b) 335)))
    (let ((a (array-ref store 331))
	  (b (array-ref store 326)))
      (when (and a b)
	(array-set! store (and16 a b) 325)))
    (let ((a (array-ref store 328)))
      (when a
	(let ((b 2))
          (array-set! store (shift16-r a b) 327))))
    (let ((a (array-ref store 330)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 329))))
    (let ((a (array-ref store 333))
	  (b (array-ref store 332)))
      (when (and a b)
	(array-set! store (or16 a b) 331)))
    (let ((a (array-ref store 335)))
      (when a
	(let ((b 1))
          (array-set! store (shift16-r a b) 334))))
    (let ((a (array-ref store 338))
	  (b (array-ref store 337)))
      (when (and a b)
	(array-set! store (and16 a b) 336))))

  ;; compute number of unknowns 
  (let ((i 0)       
	(lim (array-length store))
	(ufo 0))
    (letrec ((foo (lambda (n)
		    (cond
		     ((>= n lim) ufo)
		     ((array-ref store n) (foo (+ n 1)))
		     (#t (set! ufo (+ ufo 1))
			 (foo (+ n 1)))))))
      (when (> (foo 0) 0)
	(loop)))))

;; answer in store
;; index of wire a ?

(define (solve)
  (set! store (make-array #f (length symbols)))
  (loop)
  (format #t "~a ~%" (array-ref store (sym-index "a")))
  (format #t "~a ~%" (bin->dec (array-ref store (sym-index "a"))))
  )


  
#|

scheme@(#{ g26293}#) [36]> (solve)
(0 0 1 1 1 1 1 0 1 1 0 0 1 1 0 0) 

16076

saying output wire A should be 16,076

$216 = #t

|#


		     
